apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "Deployed image {{ .Values.profileService.image }}"
spec:
  imagePullSecrets:
    - name: regcred
  replicas: {{ .Values.profileService.replicas }}
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: "{{ .Values.profileService.image }}"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: dev
spec:
  selector:
    app: profile-service
  ports:
    - port: 3000
      targetPort: 3000
